Update build-and-test.yml

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -43,13 +43,13 @@ jobs:
         run: |
           cd build
           ../cmake/bin/cmake --build . --target protonchess
-          echo "::set-output name=build_passing::$([[ $? -eq 0 ]] && echo "Passing" || echo "Failing")\n"
+          echo "::set-output name=build_result::$([[ $? -eq 0 ]] && echo "Passing" || echo "Failing")\n"
         
       - name: Build badge
         uses: RubbaBoy/BYOB@v1.2.0
         with:
           NAME: build
           LABEL: Build
-          STATUS: ${{ steps.build.outputs.build }}
+          STATUS: ${{ steps.build.outputs.build_result }}
           COLOR: 00EEFF
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
